const minify =require('html-minifier').minify;
const fs = require('fs');

const html = fs.readFileSync("./index.html", 'utf8');
const js = fs.readFileSync("./dist/out.js", 'utf8');

const options = {
  includeAutoGeneratedTags: true,
  removeAttributeQuotes: true,
  removeComments: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  sortClassName: true,
  useShortDoctype: true,
  collapseWhitespace: true,
  minifyJs: true,
  minifyCSS: true,
};

const migratedHTML = html.replace('SCRIPT_TARGET', js)
const result = minify(migratedHTML, options);

fs.writeFileSync('dist/index.html', result)
console.log('finish!!')